%{

Description: This function is a graphics function used to plot probabilty
values vs. SCC heatmaps.  The function takes a matrix M as input.
  
% Note: M is a matrix where, when opening in the Matlab workspace 
% viewer (the panel to the left of this window) gives the
% origin in the upper-left.  This is where the 0/0 case is.  Then when
% plotting, the HeatMap function flips the vertical axis to give a plot
% where the origin is in the bottom-left. 

%}
function generateHeatmap(M)

% Create a new figure
figure1 = figure;
figure(figure1);


% Determine the min and max SCC values
minVal = min(M(:));               
maxVal = max(M(:));


% Autogenerated Code from Matlab's Editor which is used to make the tick
% marks on the Axes
axes1 = axes('Parent',figure1,'Tag','HeatMapAxes',...
    'YTickLabel',{'0','0.1','0.2','0.3','0.4','0.5','0.6','0.7','0.8','0.9','1.0'},...
    'XTickLabel',{'0','0.1','0.2','0.3','0.4','0.5','0.6','0.7','0.8','0.9','1.0'},...
    'TickLength',[0 0],...
    'CLim',[minVal maxVal],...
    'FontSize',9);
box(axes1,'on');
hold(axes1,'on');


% Create xlabel
xlabel('P_1','Units','points','FontSize',16);

% Create ylabel
ylabel('P_2','Units','points','FontSize',16);


% Now we actually plot the heatmap

% Note: Results is a matrix where, when opening in the Matlab workspace 
% viewer (the panel to the left of this window) gives the
% origin in the upper-left.  This is where the 0/0 case is.  Then when
% plotting, the HeatMap function flips the vertical axis to give a plot
% where the origin is in the bottom-left. 

ax = plot(HeatMap(M), figure1); 

%Note:   red represents values above the mean, black 
%represents the mean, and green represents values below the mean of a 
%row (gene) across all columns (samples).


% Finally, adjust the color bar so it does not interfere with the plot
C = colorbar(ax);
C.Box = 'off';
C.Position = [0.9229    0.1095    0.0357    0.8167];


end